[2024-02-04 14:06:09 +0000] [2874] [INFO] Starting gunicorn 21.2.0
[2024-02-04 14:06:09 +0000] [2874] [INFO] Listening at: http://127.0.0.1:8000 (2874)
[2024-02-04 14:06:09 +0000] [2874] [INFO] Using worker: sync
[2024-02-04 14:06:09 +0000] [2875] [INFO] Booting worker with pid: 2875
[2024-02-04 14:06:09 +0000] [2875] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2024-02-04 14:06:09 +0000] [2875] [INFO] Worker exiting (pid: 2875)
[2024-02-04 14:06:09 +0000] [2874] [ERROR] Worker (pid:2875) exited with code 3
[2024-02-04 14:06:09 +0000] [2874] [ERROR] Shutting down: Master
[2024-02-04 14:06:09 +0000] [2874] [ERROR] Reason: Worker failed to boot.
